from countryinfo import CountryInfo
country = CountryInfo('India')
print("Getting all information one by one:- ")
A=country.provinces()
B=country.alt_spellings()
C=country.area()
D=country.borders()
E=country.calling_codes()
F=country.capital()
G=country.capital_latlng()
H=country.currencies()
I=country.demonym()
J=country.translations()
K=country.iso()
L=country.languages()
M=country.latlng()
N=country.native_name()
O=country.population()
P=country.region()
Q=country.subregion()
R=country.timezones()
S=country.tld()
T=country.wiki()
print('provinces:',A)
print('alt_spellings:',B)
print('area:',C)
print('borders:',D)
print('calling_codes:',E)
print('capital:',F)
print('capital_latlng:',G)
print('currencies:',H)
print('demonym:',I)
print('Translation:',J)
print('iso:',K)
print('languages:',L)
print('latlng:',M)
print('native_name:',N)
print('population:',O)
print('region:',P)
print('subregion:',Q)
print('timezones:',R)
print('tld:',S)
print('wiki:',T)

print("Getting all information at once:-")
All_Info=country.info()
print('ALL_INFORMATION:',All_Info)


